Do you know how to properly use ethos,pathos,and logos in a speech? Inaugural Address by John F. Kennedy In 1961, the U.S was locked in a potentially explosive stalemate with the Soviet Union  and its allies.and the U.S and soviet union were stockpiling nuclear weapons, creating the possibility of a disastrous war, in this speech John F. Kennedy uses mostly pathos and Ethos to argue his point. The “Four Freedoms” Speech by Franklin D. Roosevelt in 1941, Americans did not want to be involved in World war 2 however others felt the Germans aggression threatened democracy throughout the world and that hitler must be stopped. He revives mostly pathos, appealing to fear, hope and duty. Franklin D. Roosevelt delivers a more effective speech by using pathos, Ethos, and Logos John F.Kenndey.



In “four freesons” it was ethos to ensure his credibility as a speaker he states “As your president, performing my constitutional duty to “give to the congress information of a state of the union”  this piece of evidence highlights that he is the president and he is doing his duty for our country this makes him a credibility source. In the text he also uses a lot of paths to appeal to emotions. He says “The happiness of fortune generations of Americans may depend upon how effective and immediate we can make our aid felt”. In this piece of evidence he is trying to make people fear what will happen to the later generations if he doesn't act now and also giving them hope to stand up and know that can make a better fortune for more Americans.


 Another piece of evidence that uses logos and pathos logos dealers with logic is from “The Four Freedoms" is “A free nation has the right to expect full cooperation from all groups. A free nation has the right to look to the leaders of business, of labor, and of agriculture to take the lead in stimulating effort, not among other groups but within their own groups".This shows that he relies heavily on pathos supported by logos, that he knows how to back up emotions with logic, let me state another example of logos “We need not overemphasize imperfections in the peace of Versailles. We need not harp on the failure of the democracies to deal with problems of world reconstruction”. This is a fact that he is stating saying we will not focus on problems or things that are no longer relevant. 

Some people may argue that John F. Kennedy used ethos. Logos, and pathos better than Franklin D. Roosevelt  but I strongly disagree. I found way more evidence in the Franklin D. Roosevelt's speech “The Four Freedoms”  used multiple appeals in multiple statements and backed them up to.” The fourth freedom from fear- which, translated into world terms, means a worldwide reduction of armaments to such a point and in such a thorough fashion that no nation will be in a position to commit an act of physical aggression against any neighbor- anywhere in the world”.this a wonderful piece of evidence to prove me point this shows that used pathos and logos.

 So in conclusion, I believe that Franklin D. Roosevelt delivers a more effective speech by using pathos, Ethos and Logos than John F. Kennedy I have provided many quotes that support my claim and reasoning, Franklin D. Roosevelt mostly uses  pathos, the appeal to emotion to really sway the audience while John F. Kennedy uses ethos to prove his credibility.



